"""
agents/job_agent.py
-------------------
Uses Groq (free LLM API) to:
  1. Score & rank the scraped jobs
  2. Write a catchy, personalised email digest intro
  3. Generate a short summary blurb for each job
"""

import os
import json
from groq import Groq
from utils.logger import get_logger

logger = get_logger("JobAgent")


def _get_client() -> Groq:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise EnvironmentError("GROQ_API_KEY not set in .env")
    return Groq(api_key=api_key)


def _chat(client: Groq, system: str, user: str, max_tokens: int = 1024) -> str:
    """Single-turn Groq chat completion."""
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",   # free & fast
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        max_tokens=max_tokens,
        temperature=0.7,
    )
    return response.choices[0].message.content.strip()


def rank_and_summarise(jobs: list[dict]) -> list[dict]:
    """
    Ask Groq to rank jobs by desirability for a fresh software/data grad
    and add a one-line AI summary to each.
    Returns sorted list (best first).
    """
    if not jobs:
        return jobs

    client = _get_client()

    # Build compact job list for the prompt
    compact = []
    for i, j in enumerate(jobs):
        compact.append({
            "idx": i,
            "title": j.get("title", ""),
            "company": j.get("company", ""),
            "location": j.get("location", ""),
            "tags": j.get("tags", ""),
            "source": j.get("source", ""),
        })

    prompt_jobs = json.dumps(compact, indent=2)

    system = (
        "You are a career advisor specialising in tech roles. "
        "You help students and early-career professionals find the best opportunities."
    )

    rank_prompt = (
        f"Here are {len(compact)} job listings:\n{prompt_jobs}\n\n"
        "Task:\n"
        "1. Rank ALL of them from most to least attractive for a fresh graduate or intern "
        "   targeting software engineering, SDE, data analyst, or analyst roles.\n"
        "2. For each job write a ONE-sentence (max 20 words) compelling summary.\n"
        "Return ONLY a JSON array like:\n"
        '[\n  {"idx": 0, "rank": 1, "summary": "..."}, ...\n]\n'
        "No markdown fences, no extra text."
    )

    try:
        raw = _chat(client, system, rank_prompt, max_tokens=2000)
        # Strip any accidental markdown fences
        raw = raw.strip().lstrip("```json").lstrip("```").rstrip("```").strip()
        ranked = json.loads(raw)
        # Build lookup
        rank_map = {item["idx"]: item for item in ranked}
        # Annotate original jobs
        for i, job in enumerate(jobs):
            meta = rank_map.get(i, {})
            job["rank"] = meta.get("rank", 99)
            job["ai_summary"] = meta.get("summary", "")
        jobs.sort(key=lambda x: x.get("rank", 99))
        logger.info("Jobs ranked and summarised by Groq AI")
    except Exception as e:
        logger.error(f"Groq ranking failed: {e}. Using original order.")
        for i, job in enumerate(jobs):
            job["rank"] = i + 1
            job["ai_summary"] = ""

    return jobs


def generate_email_intro(jobs: list[dict]) -> str:
    """
    Ask Groq to write an engaging 2-3 sentence intro paragraph for the digest email.
    """
    client = _get_client()

    titles = [j.get("title", "") for j in jobs[:5]]
    companies = [j.get("company", "") for j in jobs[:5]]

    system = "You write crisp, motivational career newsletter content."
    prompt = (
        f"Write a short, energetic 2-3 sentence intro for a daily job digest email. "
        f"Today's digest has {len(jobs)} curated tech job openings. "
        f"Top roles include: {', '.join(titles[:5])} at companies like {', '.join(companies[:5])}. "
        "Sound helpful and encouraging. Do NOT use emojis in excess. Plain text only."
    )

    try:
        intro = _chat(client, system, prompt, max_tokens=200)
        logger.info("Email intro generated by Groq AI")
        return intro
    except Exception as e:
        logger.error(f"Intro generation failed: {e}")
        return (
            f"Good morning! Here's your daily curated tech job digest with "
            f"{len(jobs)} fresh opportunities in software engineering, data analysis, "
            "and related fields. Apply early — great roles fill fast!")