from datetime import datetime


def build_html_email(jobs, intro):
    date_str = datetime.now().strftime("%B %d, %Y")

    job_cards = ""
    for j in jobs:
        title = j.get('title', 'Untitled Role')
        company = j.get('company', 'Unknown Company')
        location = j.get('location', 'Location not specified')
        url = j.get('url', '#')
        source = j.get('source', 'Unknown')
        tags = j.get('tags', '')
        summary = j.get('ai_summary', '')
        rank = j.get('rank', 'N/A')

        is_pune = 'pune' in location.lower()
        pune_badge = (
            '<span style="background: #16a34a; color: white; padding: 2px 8px; '
            'border-radius: 4px; font-size: 12px; font-weight: bold; margin-left: 4px;">📍 Pune</span>'
        ) if is_pune else ""

        job_cards += f"""
        <div style="background: #ffffff; border-radius: 8px; padding: 15px; margin-bottom: 15px; border: 1px solid #ddd; box-shadow: 2px 2px 5px #eee;">
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <span style="background: #ef4444; color: white; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold;">Rank #{rank}</span>
                <span>
                    <span style="background: #e2e8f0; color: #475569; padding: 2px 8px; border-radius: 4px; font-size: 12px;">{source}</span>
                    {pune_badge}
                </span>
            </div>
            <h3 style="margin: 10px 0; color: #1e293b;"><a href="{url}" style="color: #2563eb; text-decoration: none;">{title}</a></h3>
            <p style="color: #64748b; font-size: 14px; margin: 0;"><strong>{company}</strong> | {location}</p>
            <p style="color: #334155; font-size: 14px; font-style: italic; margin: 10px 0;">" {summary} "</p>
            <div style="margin-bottom: 15px;">
                <span style="background: #e0e7ff; color: #4338ca; padding: 2px 6px; border-radius: 4px; font-size: 11px; margin-right: 5px;">{tags}</span>
            </div>
            <a href="{url}" style="background: #1e293b; color: white; padding: 8px 16px; text-decoration: none; border-radius: 5px; font-size: 13px; display: inline-block;">Apply Now →</a>
        </div>
        """

    if not job_cards:
        job_cards = """
        <div style="background:#fff;border-radius:8px;padding:20px;text-align:center;color:#64748b;">
            No jobs matched today's filters. Check back tomorrow!
        </div>
        """

    return f"""
    <html>
    <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f8fafc; margin: 0; padding: 0;">
        <div style="max-width: 640px; margin: auto; background: #f8fafc;">
            <div style="background: #0f172a; color: white; padding: 30px; text-align: center;">
                <h1 style="margin: 0; font-size: 24px;">Tech Job Digest — India Focus</h1>
                <p style="margin: 5px 0 0; opacity: 0.8;">{date_str}</p>
            </div>
            <div style="padding: 20px; border-left: 5px solid #ef4444; background: #fff; margin: 20px; border-radius: 0 8px 8px 0;">
                <p style="color: #334155; font-size: 16px; line-height: 1.5;">{intro}</p>
            </div>
            <div style="padding: 0 20px;">
                {job_cards}
            </div>
            <div style="text-align: center; padding: 30px; color: #94a3b8; font-size: 12px;">
                Generated by AI Job Agent &bull; Sources: Greenhouse, Lever, Naukri, Internshala, JobSavior, Jobsora, Apna, RemoteOK, Remotive, Jobicy, Arbeitnow, WeWorkRemotely
            </div>
        </div>
    </body>
    </html>
    """


def build_plain_email(jobs, intro):
    body = f"{intro}\n\n"
    if not jobs:
        body += "No jobs matched today's filters. Check back tomorrow!\n"
        return body
    for j in jobs:
        title = j.get('title', 'Untitled Role')
        company = j.get('company', 'Unknown Company')
        url = j.get('url', '#')
        body += f"- {title} at {company}: {url}\n"
    return body
